In [3]:
import pandas as pd

In [4]:
df = pd.read_csv(r"C:\Users\Adrita Deshmukhya\OneDrive\Desktop\Personal_Financial_Health\data\NFWBS_PUF_2016_data.csv")

In [5]:
df.head()

,PUF_ID,sample,fpl,SWB_1,SWB_2,SWB_3,FWBscore,FWB1_1,FWB1_2,FWB1_3,...,PPMSACAT,PPREG4,PPREG9,PPT01,PPT25,PPT612,PPT1317,PPT18OV,PCTLT200FPL,finalwt
0,10350,2,3,5,5,6,55,3,3,3,...,1,4,8,0,0,0,0,1,0,0.367292
1,7740,1,3,6,6,6,51,2,2,3,...,1,2,3,0,0,0,0,2,0,1.327561
2,13699,1,3,4,3,4,49,3,3,3,...,1,4,9,0,0,0,1,2,1,0.835156
3,7267,1,3,6,6,6,49,3,3,3,...,1,3,7,0,0,0,0,1,0,1.410871
4,7375,1,3,4,4,4,49,3,3,3,...,1,2,4,0,0,1,0,4,1,4.260668

In [6]:
print("Shape:", df.shape)
print("\nColumns:")
print(df.columns.tolist())

Shape: (6394, 217)

Columns:
['PUF_ID', 'sample', 'fpl', 'SWB_1', 'SWB_2', 'SWB_3', 'FWBscore', 'FWB1_1', 'FWB1_2', 'FWB1_3', 'FWB1_4', 'FWB1_5', 'FWB1_6', 'FWB2_1', 'FWB2_2', 'FWB2_3', 'FWB2_4', 'FSscore', 'FS1_1', 'FS1_2', 'FS1_3', 'FS1_4', 'FS1_5', 'FS1_6', 'FS1_7', 'FS2_1', 'FS2_2', 'FS2_3', 'SUBKNOWL1', 'ACT1_1', 'ACT1_2', 'FINGOALS', 'PROPPLAN_1', 'PROPPLAN_2', 'PROPPLAN_3', 'PROPPLAN_4', 'MANAGE1_1', 'MANAGE1_2', 'MANAGE1_3', 'MANAGE1_4', 'SAVEHABIT', 'FRUGALITY', 'AUTOMATED_1', 'AUTOMATED_2', 'ASK1_1', 'ASK1_2', 'SUBNUMERACY2', 'SUBNUMERACY1', 'CHANGEABLE', 'GOALCONF', 'LMscore', 'FINKNOWL1', 'FINKNOWL2', 'FINKNOWL3', 'FK1correct', 'FK2correct', 'FK3correct', 'KHscore', 'KHKNOWL1', 'KHKNOWL2', 'KHKNOWL3', 'KHKNOWL4', 'KHKNOWL5', 'KHKNOWL6', 'KHKNOWL7', 'KHKNOWL8', 'KHKNOWL9', 'KH1correct', 'KH2correct', 'KH3correct', 'KH4correct', 'KH5correct', 'KH6correct', 'KH7correct', 'KH8correct', 'KH9correct', 'ENDSMEET', 'HOUSING', 'LIVINGARRANGEMENT', 'HOUSERANGES', 'IMPUTATION_FLAG', 'VALUERANGES', 'MORTGAGE', 'SAVINGSRANGES', 'PRODHAVE_1', 'PRODHAVE_2', 'PRODHAVE_3', 'PRODHAVE_4', 'PRODHAVE_5', 'PRODHAVE_6', 'PRODHAVE_7', 'PRODHAVE_8', 'PRODHAVE_9', 'PRODUSE_1', 'PRODUSE_2', 'PRODUSE_3', 'PRODUSE_4', 'PRODUSE_5', 'PRODUSE_6', 'CONSPROTECT1', 'CONSPROTECT2', 'CONSPROTECT3', 'EARNERS', 'VOLATILITY', 'SNAP', 'MATHARDSHIP_1', 'MATHARDSHIP_2', 'MATHARDSHIP_3', 'MATHARDSHIP_4', 'MATHARDSHIP_5', 'MATHARDSHIP_6', 'COLLECT', 'REJECTED_1', 'REJECTED_2', 'ABSORBSHOCK', 'BENEFITS_1', 'BENEFITS_2', 'BENEFITS_3', 'BENEFITS_4', 'BENEFITS_5', 'FRAUD2', 'COVERCOSTS', 'BORROW_1', 'BORROW_2', 'SHOCKS_1', 'SHOCKS_2', 'SHOCKS_3', 'SHOCKS_4', 'SHOCKS_5', 'SHOCKS_6', 'SHOCKS_7', 'SHOCKS_8', 'SHOCKS_9', 'SHOCKS_10', 'SHOCKS_11', 'SHOCKS_12', 'MANAGE2', 'PAIDHELP', 'HSLOC', 'PAREDUC', 'FINSOC2_1', 'FINSOC2_2', 'FINSOC2_3', 'FINSOC2_4', 'FINSOC2_5', 'FINSOC2_6', 'FINSOC2_7', 'OBJNUMERACY1', 'ON2correct', 'ON1correct', 'MATERIALISM_1', 'MATERIALISM_2', 'MATERIALISM_3', 'CONNECT', 'HEALTH', 'SCFHORIZON', 'DISCOUNT', 'MEMLOSS', 'DISTRESS', 'SELFCONTROL_1', 'SELFCONTROL_2', 'SELFCONTROL_3', 'OUTLOOK_1', 'OUTLOOK_2', 'INTERCONNECTIONS_1', 'INTERCONNECTIONS_2', 'INTERCONNECTIONS_3', 'INTERCONNECTIONS_4', 'INTERCONNECTIONS_5', 'INTERCONNECTIONS_6', 'INTERCONNECTIONS_7', 'INTERCONNECTIONS_8', 'INTERCONNECTIONS_9', 'INTERCONNECTIONS_10', 'PEM', 'HOUSESAT', 'SOCSEC1', 'SOCSEC2', 'SOCSEC3', 'LIFEEXPECT', 'HHEDUC', 'KIDS_NoChildren', 'KIDS_1', 'KIDS_2', 'KIDS_3', 'KIDS_4', 'EMPLOY', 'EMPLOY1_1', 'EMPLOY1_2', 'EMPLOY1_3', 'EMPLOY1_4', 'EMPLOY1_5', 'EMPLOY1_6', 'EMPLOY1_7', 'EMPLOY1_8', 'EMPLOY1_9', 'RETIRE', 'MILITARY', 'Military_Status', 'agecat', 'generation', 'PPEDUC', 'PPETHM', 'PPGENDER', 'PPHHSIZE', 'PPINCIMP', 'PPMARIT', 'PPMSACAT', 'PPREG4', 'PPREG9', 'PPT01', 'PPT25', 'PPT612', 'PPT1317', 'PPT18OV', 'PCTLT200FPL', 'finalwt']

In [7]:
df.info()
df.isnull().sum()

<class 'pandas.DataFrame'>
RangeIndex: 6394 entries, 0 to 6393
Columns: 217 entries, PUF_ID to finalwt
dtypes: float64(2), int64(215)
memory usage: 10.6 MB

PUF_ID         0
sample         0
fpl            0
SWB_1          0
SWB_2          0
              ..
PPT612         0
PPT1317        0
PPT18OV        0
PCTLT200FPL    0
finalwt        0
Length: 217, dtype: int64

In [8]:
print(df.shape)
print(df.columns.tolist())

(6394, 217)
['PUF_ID', 'sample', 'fpl', 'SWB_1', 'SWB_2', 'SWB_3', 'FWBscore', 'FWB1_1', 'FWB1_2', 'FWB1_3', 'FWB1_4', 'FWB1_5', 'FWB1_6', 'FWB2_1', 'FWB2_2', 'FWB2_3', 'FWB2_4', 'FSscore', 'FS1_1', 'FS1_2', 'FS1_3', 'FS1_4', 'FS1_5', 'FS1_6', 'FS1_7', 'FS2_1', 'FS2_2', 'FS2_3', 'SUBKNOWL1', 'ACT1_1', 'ACT1_2', 'FINGOALS', 'PROPPLAN_1', 'PROPPLAN_2', 'PROPPLAN_3', 'PROPPLAN_4', 'MANAGE1_1', 'MANAGE1_2', 'MANAGE1_3', 'MANAGE1_4', 'SAVEHABIT', 'FRUGALITY', 'AUTOMATED_1', 'AUTOMATED_2', 'ASK1_1', 'ASK1_2', 'SUBNUMERACY2', 'SUBNUMERACY1', 'CHANGEABLE', 'GOALCONF', 'LMscore', 'FINKNOWL1', 'FINKNOWL2', 'FINKNOWL3', 'FK1correct', 'FK2correct', 'FK3correct', 'KHscore', 'KHKNOWL1', 'KHKNOWL2', 'KHKNOWL3', 'KHKNOWL4', 'KHKNOWL5', 'KHKNOWL6', 'KHKNOWL7', 'KHKNOWL8', 'KHKNOWL9', 'KH1correct', 'KH2correct', 'KH3correct', 'KH4correct', 'KH5correct', 'KH6correct', 'KH7correct', 'KH8correct', 'KH9correct', 'ENDSMEET', 'HOUSING', 'LIVINGARRANGEMENT', 'HOUSERANGES', 'IMPUTATION_FLAG', 'VALUERANGES', 'MORTGAGE', 'SAVINGSRANGES', 'PRODHAVE_1', 'PRODHAVE_2', 'PRODHAVE_3', 'PRODHAVE_4', 'PRODHAVE_5', 'PRODHAVE_6', 'PRODHAVE_7', 'PRODHAVE_8', 'PRODHAVE_9', 'PRODUSE_1', 'PRODUSE_2', 'PRODUSE_3', 'PRODUSE_4', 'PRODUSE_5', 'PRODUSE_6', 'CONSPROTECT1', 'CONSPROTECT2', 'CONSPROTECT3', 'EARNERS', 'VOLATILITY', 'SNAP', 'MATHARDSHIP_1', 'MATHARDSHIP_2', 'MATHARDSHIP_3', 'MATHARDSHIP_4', 'MATHARDSHIP_5', 'MATHARDSHIP_6', 'COLLECT', 'REJECTED_1', 'REJECTED_2', 'ABSORBSHOCK', 'BENEFITS_1', 'BENEFITS_2', 'BENEFITS_3', 'BENEFITS_4', 'BENEFITS_5', 'FRAUD2', 'COVERCOSTS', 'BORROW_1', 'BORROW_2', 'SHOCKS_1', 'SHOCKS_2', 'SHOCKS_3', 'SHOCKS_4', 'SHOCKS_5', 'SHOCKS_6', 'SHOCKS_7', 'SHOCKS_8', 'SHOCKS_9', 'SHOCKS_10', 'SHOCKS_11', 'SHOCKS_12', 'MANAGE2', 'PAIDHELP', 'HSLOC', 'PAREDUC', 'FINSOC2_1', 'FINSOC2_2', 'FINSOC2_3', 'FINSOC2_4', 'FINSOC2_5', 'FINSOC2_6', 'FINSOC2_7', 'OBJNUMERACY1', 'ON2correct', 'ON1correct', 'MATERIALISM_1', 'MATERIALISM_2', 'MATERIALISM_3', 'CONNECT', 'HEALTH', 'SCFHORIZON', 'DISCOUNT', 'MEMLOSS', 'DISTRESS', 'SELFCONTROL_1', 'SELFCONTROL_2', 'SELFCONTROL_3', 'OUTLOOK_1', 'OUTLOOK_2', 'INTERCONNECTIONS_1', 'INTERCONNECTIONS_2', 'INTERCONNECTIONS_3', 'INTERCONNECTIONS_4', 'INTERCONNECTIONS_5', 'INTERCONNECTIONS_6', 'INTERCONNECTIONS_7', 'INTERCONNECTIONS_8', 'INTERCONNECTIONS_9', 'INTERCONNECTIONS_10', 'PEM', 'HOUSESAT', 'SOCSEC1', 'SOCSEC2', 'SOCSEC3', 'LIFEEXPECT', 'HHEDUC', 'KIDS_NoChildren', 'KIDS_1', 'KIDS_2', 'KIDS_3', 'KIDS_4', 'EMPLOY', 'EMPLOY1_1', 'EMPLOY1_2', 'EMPLOY1_3', 'EMPLOY1_4', 'EMPLOY1_5', 'EMPLOY1_6', 'EMPLOY1_7', 'EMPLOY1_8', 'EMPLOY1_9', 'RETIRE', 'MILITARY', 'Military_Status', 'agecat', 'generation', 'PPEDUC', 'PPETHM', 'PPGENDER', 'PPHHSIZE', 'PPINCIMP', 'PPMARIT', 'PPMSACAT', 'PPREG4', 'PPREG9', 'PPT01', 'PPT25', 'PPT612', 'PPT1317', 'PPT18OV', 'PCTLT200FPL', 'finalwt']

In [9]:
df["FWBscore"].describe()

count    6394.000000
mean       56.034094
std        14.154676
min        -4.000000
25%        48.000000
50%        56.000000
75%        65.000000
max        95.000000
Name: FWBscore, dtype: float64

In [9]:
df["FWBscore"].head(20)

0     55
1     51
2     49
3     49
4     49
5     67
6     51
7     47
8     43
9     58
10    78
11    62
12    50
13    40
14    61
15    69
16    37
17    52
18    69
19    67
Name: FWBscore, dtype: int64

In [10]:
df["FWBscore"].nunique()

79

In [11]:
print("Minimum:", df["FWBscore"].min())
print("Maximum:", df["FWBscore"].max())

Minimum: -4
Maximum: 95

In [12]:
financial_columns = [
    "FWBscore",
    "FSscore",
    "PPINCIMP",
    "SAVINGSRANGES",
    "MORTGAGE",
    "ENDSMEET",
    "ABSORBSHOCK",
    "COLLECT",
    "VOLATILITY",
    "EARNERS",
    "EMPLOY",
    "agecat",
    "PPEDUC"
]

df[financial_columns].head()

,FWBscore,FSscore,PPINCIMP,SAVINGSRANGES,MORTGAGE,ENDSMEET,ABSORBSHOCK,COLLECT,VOLATILITY,EARNERS,EMPLOY,agecat,PPEDUC
0,55,44,7,6,2,2,4,1,2,1,8,8,4
1,51,43,6,2,2,2,3,1,2,2,2,3,2
2,49,42,6,4,2,1,4,0,3,2,2,3,3
3,49,42,8,-1,-2,-1,8,-1,-1,-1,99,3,2
4,49,42,7,98,-2,2,2,8,2,2,2,2,2

In [13]:
df[financial_columns].describe()

,FWBscore,FSscore,PPINCIMP,SAVINGSRANGES,MORTGAGE,ENDSMEET,ABSORBSHOCK,COLLECT,VOLATILITY,EARNERS,EMPLOY,agecat,PPEDUC
count,6394.000000,6394.000000,6394.000000,6394.000000,6394.000000,6394.000000,6394.000000,6394.000000,6394.000000,6394.000000,6394.000000,6394.000000,6394.000000
mean,56.034094,50.719112,5.510635,21.365499,9.720988,1.444948,3.517204,0.420238,1.313262,1.634970,6.063341,4.450422,3.160776
std,14.154676,12.656921,2.671075,36.256298,29.070458,0.661932,1.514031,1.531556,0.636196,0.641885,12.917475,2.120741,1.178349
min,-4.000000,-1.000000,1.000000,-1.000000,-2.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,1.000000,1.000000,1.000000
25%,48.000000,42.000000,3.000000,4.000000,-2.000000,1.000000,3.000000,0.000000,1.000000,1.000000,2.000000,3.000000,2.000000
50%,56.000000,50.000000,6.000000,5.000000,1.000000,1.000000,4.000000,0.000000,1.000000,2.000000,3.000000,4.000000,3.000000
75%,65.000000,57.000000,8.000000,7.000000,2.000000,2.000000,4.000000,0.000000,2.000000,2.000000,8.000000,6.000000,4.000000
max,95.000000,85.000000,9.000000,99.000000,99.000000,3.000000,8.000000,8.000000,3.000000,3.000000,99.000000,8.000000,5.000000

In [14]:
# Check special values in important columns

columns_to_check = [
    "FWBscore",
    "FSscore",
    "PPINCIMP",
    "SAVINGSRANGES",
    "MORTGAGE",
    "ENDSMEET",
    "ABSORBSHOCK",
    "COLLECT",
    "VOLATILITY",
    "EARNERS",
    "EMPLOY",
    "agecat",
    "PPEDUC"
]

for col in columns_to_check:
    print(f"\n--- {col} ---")
    print(df[col].value_counts().sort_index())

--- FWBscore ---
FWBscore
-4      1
-1      4
 14    21
 16     3
 17     8
       ..
 87     7
 88    14
 89    11
 90     2
 95    69
Name: count, Length: 79, dtype: int64

--- FSscore ---
FSscore
-1       8
 5       2
 8       2
 9       1
 10      8
      ...
 79     44
 80     15
 81     16
 82     46
 85    114
Name: count, Length: 77, dtype: int64

--- PPINCIMP ---
PPINCIMP
1     719
2     506
3     614
4     467
5     505
6     651
7     955
8    1115
9     862
Name: count, dtype: int64

--- SAVINGSRANGES ---
SAVINGSRANGES
-1       38
 1      440
 2      385
 3      682
 4      931
 5     1093
 6      845
 7      834
 98     158
 99     988
Name: count, dtype: int64

--- MORTGAGE ---
MORTGAGE
-2     2230
-1       56
 1     1512
 2     1361
 3      622
 98     115
 99     498
Name: count, dtype: int64

--- ENDSMEET ---
ENDSMEET
-1      44
 1    3896
 2    1975
 3     479
Name: count, dtype: int64

--- ABSORBSHOCK ---
ABSORBSHOCK
-1      37
 1     811
 2     426
 3     937
 4    3853
 8     330
Name: count, dtype: int64

--- COLLECT ---
COLLECT
-1      55
 0    5263
 1     838
 8     238
Name: count, dtype: int64

--- VOLATILITY ---
VOLATILITY
-1      64
 1    4613
 2    1303
 3     414
Name: count, dtype: int64

--- EARNERS ---
EARNERS
-1      78
 1    2442
 2    3532
 3     342
Name: count, dtype: int64

--- EMPLOY ---
EMPLOY
1      418
2     2493
3      433
4      358
5      225
6      269
7      245
8     1837
99     116
Name: count, dtype: int64

--- agecat ---
agecat
1     414
2    1116
3     828
4    1075
5     708
6    1021
7     496
8     736
Name: count, dtype: int64

--- PPEDUC ---
PPEDUC
1     429
2    1622
3    1933
4    1312
5    1098
Name: count, dtype: int64

In [15]:
print("FWBscore special values:")
print(df.loc[~df["FWBscore"].between(0, 100), "FWBscore"].value_counts().sort_index())

FWBscore special values:
FWBscore
-4    1
-1    4
Name: count, dtype: int64

In [16]:
df_model = df[df["FWBscore"] >= 0].copy()

print("Original rows:", len(df))
print("Rows after cleaning:", len(df_model))
print("Removed rows:", len(df) - len(df_model))

Original rows: 6394
Rows after cleaning: 6389
Removed rows: 5

In [17]:
print(df_model["FWBscore"].min())
print(df_model["FWBscore"].max())

14
95

In [18]:
df_model = df[df["FWBscore"] >= 0].copy()

print("Original rows:", len(df))
print("Rows after cleaning:", len(df_model))
print("Removed rows:", len(df) - len(df_model))
print("\nFWBscore range:")
print(df_model["FWBscore"].min(), "to", df_model["FWBscore"].max())

Original rows: 6394
Rows after cleaning: 6389
Removed rows: 5

FWBscore range:
14 to 95

In [19]:
for i, col in enumerate(df_model.columns, start=1):
    print(i, col)

1 PUF_ID
2 sample
3 fpl
4 SWB_1
5 SWB_2
6 SWB_3
7 FWBscore
8 FWB1_1
9 FWB1_2
10 FWB1_3
11 FWB1_4
12 FWB1_5
13 FWB1_6
14 FWB2_1
15 FWB2_2
16 FWB2_3
17 FWB2_4
18 FSscore
19 FS1_1
20 FS1_2
21 FS1_3
22 FS1_4
23 FS1_5
24 FS1_6
25 FS1_7
26 FS2_1
27 FS2_2
28 FS2_3
29 SUBKNOWL1
30 ACT1_1
31 ACT1_2
32 FINGOALS
33 PROPPLAN_1
34 PROPPLAN_2
35 PROPPLAN_3
36 PROPPLAN_4
37 MANAGE1_1
38 MANAGE1_2
39 MANAGE1_3
40 MANAGE1_4
41 SAVEHABIT
42 FRUGALITY
43 AUTOMATED_1
44 AUTOMATED_2
45 ASK1_1
46 ASK1_2
47 SUBNUMERACY2
48 SUBNUMERACY1
49 CHANGEABLE
50 GOALCONF
51 LMscore
52 FINKNOWL1
53 FINKNOWL2
54 FINKNOWL3
55 FK1correct
56 FK2correct
57 FK3correct
58 KHscore
59 KHKNOWL1
60 KHKNOWL2
61 KHKNOWL3
62 KHKNOWL4
63 KHKNOWL5
64 KHKNOWL6
65 KHKNOWL7
66 KHKNOWL8
67 KHKNOWL9
68 KH1correct
69 KH2correct
70 KH3correct
71 KH4correct
72 KH5correct
73 KH6correct
74 KH7correct
75 KH8correct
76 KH9correct
77 ENDSMEET
78 HOUSING
79 LIVINGARRANGEMENT
80 HOUSERANGES
81 IMPUTATION_FLAG
82 VALUERANGES
83 MORTGAGE
84 SAVINGSRANGES
85 PRODHAVE_1
86 PRODHAVE_2
87 PRODHAVE_3
88 PRODHAVE_4
89 PRODHAVE_5
90 PRODHAVE_6
91 PRODHAVE_7
92 PRODHAVE_8
93 PRODHAVE_9
94 PRODUSE_1
95 PRODUSE_2
96 PRODUSE_3
97 PRODUSE_4
98 PRODUSE_5
99 PRODUSE_6
100 CONSPROTECT1
101 CONSPROTECT2
102 CONSPROTECT3
103 EARNERS
104 VOLATILITY
105 SNAP
106 MATHARDSHIP_1
107 MATHARDSHIP_2
108 MATHARDSHIP_3
109 MATHARDSHIP_4
110 MATHARDSHIP_5
111 MATHARDSHIP_6
112 COLLECT
113 REJECTED_1
114 REJECTED_2
115 ABSORBSHOCK
116 BENEFITS_1
117 BENEFITS_2
118 BENEFITS_3
119 BENEFITS_4
120 BENEFITS_5
121 FRAUD2
122 COVERCOSTS
123 BORROW_1
124 BORROW_2
125 SHOCKS_1
126 SHOCKS_2
127 SHOCKS_3
128 SHOCKS_4
129 SHOCKS_5
130 SHOCKS_6
131 SHOCKS_7
132 SHOCKS_8
133 SHOCKS_9
134 SHOCKS_10
135 SHOCKS_11
136 SHOCKS_12
137 MANAGE2
138 PAIDHELP
139 HSLOC
140 PAREDUC
141 FINSOC2_1
142 FINSOC2_2
143 FINSOC2_3
144 FINSOC2_4
145 FINSOC2_5
146 FINSOC2_6
147 FINSOC2_7
148 OBJNUMERACY1
149 ON2correct
150 ON1correct
151 MATERIALISM_1
152 MATERIALISM_2
153 MATERIALISM_3
154 CONNECT
155 HEALTH
156 SCFHORIZON
157 DISCOUNT
158 MEMLOSS
159 DISTRESS
160 SELFCONTROL_1
161 SELFCONTROL_2
162 SELFCONTROL_3
163 OUTLOOK_1
164 OUTLOOK_2
165 INTERCONNECTIONS_1
166 INTERCONNECTIONS_2
167 INTERCONNECTIONS_3
168 INTERCONNECTIONS_4
169 INTERCONNECTIONS_5
170 INTERCONNECTIONS_6
171 INTERCONNECTIONS_7
172 INTERCONNECTIONS_8
173 INTERCONNECTIONS_9
174 INTERCONNECTIONS_10
175 PEM
176 HOUSESAT
177 SOCSEC1
178 SOCSEC2
179 SOCSEC3
180 LIFEEXPECT
181 HHEDUC
182 KIDS_NoChildren
183 KIDS_1
184 KIDS_2
185 KIDS_3
186 KIDS_4
187 EMPLOY
188 EMPLOY1_1
189 EMPLOY1_2
190 EMPLOY1_3
191 EMPLOY1_4
192 EMPLOY1_5
193 EMPLOY1_6
194 EMPLOY1_7
195 EMPLOY1_8
196 EMPLOY1_9
197 RETIRE
198 MILITARY
199 Military_Status
200 agecat
201 generation
202 PPEDUC
203 PPETHM
204 PPGENDER
205 PPHHSIZE
206 PPINCIMP
207 PPMARIT
208 PPMSACAT
209 PPREG4
210 PPREG9
211 PPT01
212 PPT25
213 PPT612
214 PPT1317
215 PPT18OV
216 PCTLT200FPL
217 finalwt

In [20]:
exclude_columns = [
    "PUF_ID",
    "FWBscore",

    # FWB scale items - target leakage
    "FWB1_1", "FWB1_2", "FWB1_3",
    "FWB1_4", "FWB1_5", "FWB1_6",
    "FWB2_1", "FWB2_2", "FWB2_3", "FWB2_4"
]

print("Excluded:", len(exclude_columns))

Excluded: 12

In [21]:
exclude_columns = [
    "PUF_ID",
    "FWBscore",
    "FWB1_1", "FWB1_2", "FWB1_3",
    "FWB1_4", "FWB1_5", "FWB1_6",
    "FWB2_1", "FWB2_2", "FWB2_3", "FWB2_4"
]

print("Excluded:", len(exclude_columns))

Excluded: 12

In [22]:
candidate_features = [
    # Income & savings
    "PPINCIMP",
    "SAVINGSRANGES",
    "ENDSMEET",
    "ABSORBSHOCK",
    "COLLECT",
    "VOLATILITY",

    # Employment & household
    "EMPLOY",
    "EARNERS",
    "PPHHSIZE",

    # Demographics
    "agecat",
    "PPEDUC",
    "PPGENDER",
    "PPMARIT",

    # Housing / financial obligations
    "HOUSING",
    "MORTGAGE",

    # Financial behaviour / planning
    "FINGOALS",
    "PROPPLAN_1",
    "PROPPLAN_2",
    "PROPPLAN_3",
    "PROPPLAN_4",
    "SAVEHABIT",
    "FRUGALITY",

    # Financial knowledge / capability
    "FINKNOWL1",
    "FINKNOWL2",
    "FINKNOWL3",
    
    # Financial shocks / difficulties
    "MATHARDSHIP_1",
    "MATHARDSHIP_2",
    "MATHARDSHIP_3",
    "MATHARDSHIP_4",
    "MATHARDSHIP_5",
    "MATHARDSHIP_6",
    
    # Outlook / self-control
    "SELFCONTROL_1",
    "SELFCONTROL_2",
    "SELFCONTROL_3",
    "OUTLOOK_1",
    "OUTLOOK_2"
]

print("Number of candidate features:", len(candidate_features))

Number of candidate features: 36

In [23]:
missing_features = [
    col for col in candidate_features
    if col not in df_model.columns
]

print("Missing features:", missing_features)

Missing features: []

In [24]:
for col in candidate_features:
    special = df_model.loc[
        ~df_model[col].between(0, 100),
        col
    ].value_counts().sort_index()

    if len(special) > 0:
        print(f"\n{col}:")
        print(special)

SAVINGSRANGES:
SAVINGSRANGES
-1    36
Name: count, dtype: int64

ENDSMEET:
ENDSMEET
-1    42
Name: count, dtype: int64

ABSORBSHOCK:
ABSORBSHOCK
-1    35
Name: count, dtype: int64

COLLECT:
COLLECT
-1    52
Name: count, dtype: int64

VOLATILITY:
VOLATILITY
-1    61
Name: count, dtype: int64

EARNERS:
EARNERS
-1    75
Name: count, dtype: int64

HOUSING:
HOUSING
-1    39
Name: count, dtype: int64

MORTGAGE:
MORTGAGE
-2    2226
-1      56
Name: count, dtype: int64

FINGOALS:
FINGOALS
-1    74
Name: count, dtype: int64

PROPPLAN_1:
PROPPLAN_1
-1    6
Name: count, dtype: int64

PROPPLAN_2:
PROPPLAN_2
-1    6
Name: count, dtype: int64

PROPPLAN_3:
PROPPLAN_3
-1    6
Name: count, dtype: int64

PROPPLAN_4:
PROPPLAN_4
-1    6
Name: count, dtype: int64

SAVEHABIT:
SAVEHABIT
-1    16
Name: count, dtype: int64

FRUGALITY:
FRUGALITY
-1    12
Name: count, dtype: int64

FINKNOWL1:
FINKNOWL1
-1    27
Name: count, dtype: int64

FINKNOWL2:
FINKNOWL2
-1    35
Name: count, dtype: int64

FINKNOWL3:
FINKNOWL3
-1    42
Name: count, dtype: int64

MATHARDSHIP_1:
MATHARDSHIP_1
-1    24
Name: count, dtype: int64

MATHARDSHIP_2:
MATHARDSHIP_2
-1    24
Name: count, dtype: int64

MATHARDSHIP_3:
MATHARDSHIP_3
-1    23
Name: count, dtype: int64

MATHARDSHIP_4:
MATHARDSHIP_4
-1    24
Name: count, dtype: int64

MATHARDSHIP_5:
MATHARDSHIP_5
-1    22
Name: count, dtype: int64

MATHARDSHIP_6:
MATHARDSHIP_6
-1    25
Name: count, dtype: int64

SELFCONTROL_1:
SELFCONTROL_1
-1    51
Name: count, dtype: int64

SELFCONTROL_2:
SELFCONTROL_2
-1    47
Name: count, dtype: int64

SELFCONTROL_3:
SELFCONTROL_3
-1    45
Name: count, dtype: int64

OUTLOOK_1:
OUTLOOK_1
-1    77
Name: count, dtype: int64

OUTLOOK_2:
OUTLOOK_2
-1    81
Name: count, dtype: int64

In [25]:
import numpy as np

X = df_model[candidate_features].copy()

X = X.replace(-1, np.nan)

print("Missing values after replacing -1:")
print(X.isnull().sum()[X.isnull().sum() > 0])

Missing values after replacing -1:
SAVINGSRANGES    36
ENDSMEET         42
ABSORBSHOCK      35
COLLECT          52
VOLATILITY       61
EARNERS          75
HOUSING          39
MORTGAGE         56
FINGOALS         74
PROPPLAN_1        6
PROPPLAN_2        6
PROPPLAN_3        6
PROPPLAN_4        6
SAVEHABIT        16
FRUGALITY        12
FINKNOWL1        27
FINKNOWL2        35
FINKNOWL3        42
MATHARDSHIP_1    24
MATHARDSHIP_2    24
MATHARDSHIP_3    23
MATHARDSHIP_4    24
MATHARDSHIP_5    22
MATHARDSHIP_6    25
SELFCONTROL_1    51
SELFCONTROL_2    47
SELFCONTROL_3    45
OUTLOOK_1        77
OUTLOOK_2        81
dtype: int64

In [27]:
import numpy as np
from sklearn.ensemble import RandomForestRegressor
from sklearn.impute import SimpleImputer
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.model_selection import train_test_split

# 1. Impute missing values (using median strategy for survey ordinal data)
imputer = SimpleImputer(strategy='median')
X_imputed = pd.DataFrame(imputer.fit_transform(X), columns=X.columns)

# 2. Define Target variable
y = df_model['FWBscore']

# 3. Train/Test Split
X_train, X_test, y_train, y_test = train_test_split(
    X_imputed, y, test_size=0.2, random_state=42
)

# 4. Train Random Forest Model
model = RandomForestRegressor(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

# 5. Evaluate
y_pred = model.predict(X_test)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))

print(f'R2 Score: {r2_score(y_test, y_pred):.3f}')
print(f'RMSE: {rmse:.3f}')

R2 Score: 0.642
RMSE: 8.339

In [29]:
import numpy as np
from sklearn.ensemble import RandomForestRegressor
from sklearn.impute import SimpleImputer
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.model_selection import train_test_split

# 1. Impute missing values
imputer = SimpleImputer(strategy='median')
X_imputed = pd.DataFrame(imputer.fit_transform(X), columns=X.columns)

# 2. Define Target variable
y = df_model['FWBscore']

# 3. Train/Test Split
X_train, X_test, y_train, y_test = train_test_split(
    X_imputed, y, test_size=0.2, random_state=42
)

# 4. Train Random Forest Model
model = RandomForestRegressor(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

# 5. Evaluate
y_pred = model.predict(X_test)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))

print(f'R2 Score: {r2_score(y_test, y_pred):.3f}')
print(f'RMSE: {rmse:.3f}')

R2 Score: 0.642
RMSE: 8.339

In [30]:
import os
import joblib

# Create models directory if it doesn't exist
os.makedirs("../models", exist_ok=True)

# Save model and imputer
joblib.dump(model, "../models/financial_health_model.pkl")
joblib.dump(imputer, "../models/imputer.pkl")
print("Model and imputer saved successfully!")

Model and imputer saved successfully!